# Generated by Django 5.2.15 on 2026-06-06 20:02

import django.db.models.deletion
import scolta_django.searchable
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=(scolta_django.searchable.SearchableMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main HTML body')),
                ('section', models.CharField(blank=True, db_index=True, max_length=64)),
                ('difficulty', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=32)),
                ('git_version', models.CharField(blank=True, max_length=32, verbose_name='Git version')),
                ('weight', models.IntegerField(default=0)),
                ('compared_systems', models.CharField(blank=True, help_text='Comma-separated list of compared systems', max_length=255)),
                ('applies_to', models.CharField(blank=True, max_length=128)),
                ('verdict', wagtail.fields.RichTextField(blank=True)),
                ('feature_table', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Comparison',
            },
            bases=(scolta_django.searchable.SearchableMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='DocumentationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main HTML body')),
                ('section', models.CharField(blank=True, db_index=True, max_length=64)),
                ('difficulty', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=32)),
                ('git_version', models.CharField(blank=True, max_length=32, verbose_name='Git version')),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Documentation page',
            },
            bases=(scolta_django.searchable.SearchableMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Home page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main HTML body')),
                ('section', models.CharField(blank=True, db_index=True, max_length=64)),
                ('difficulty', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=32)),
                ('git_version', models.CharField(blank=True, max_length=32, verbose_name='Git version')),
                ('weight', models.IntegerField(default=0)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Tip',
            },
            bases=(scolta_django.searchable.SearchableMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main HTML body')),
                ('section', models.CharField(blank=True, db_index=True, max_length=64)),
                ('difficulty', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=32)),
                ('git_version', models.CharField(blank=True, max_length=32, verbose_name='Git version')),
                ('weight', models.IntegerField(default=0)),
                ('estimated_time', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Tutorial',
            },
            bases=(scolta_django.searchable.SearchableMixin, 'wagtailcore.page'),
        ),
    ]
